### ISSUE TITLE
Very small floating point numbers cause ValueError

### ISSUE THREAD

**Issue by JoshuaArking** [brent-stone/CAN_Reverse_Engineering#3]
(Copied from pull request: [Fix for very small floating point numbers causing ValueError](https://github.com/brent-stone/CAN_Reverse_Engineering/pull/2))

While using data recorded from a 2018 Mazda 3, Semantic Analysis fails with:

Traceback (most recent call last): File "/home/mint/PycharmProjects/CAN_Reverse_Engineering/Pipeline_multi-file/Main.py", line 35, in <module> cluster_dict, linkage_matrix = sample.cluster_signals(corr_matrix) File "/home/mint/PycharmProjects/CAN_Reverse_Engineering/Pipeline_multi-file/Sample.py", line 245, in cluster_signals force_clustering) # type: dict, ndarray File "/home/mint/PycharmProjects/CAN_Reverse_Engineering/Pipeline_multi-file/SemanticAnalysis.py", line 82, in signal_clustering Z = linkage(Y, method='single', optimal_ordering=True) File "/home/mint/anaconda3/envs/CAN_Reverse_Engineering/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 1075, in linkage return optimal_leaf_ordering(result, y) File "/home/mint/anaconda3/envs/CAN_Reverse_Engineering/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 1530, in optimal_leaf_ordering is_valid_linkage(Z, throw=True, name='Z') File "/home/mint/anaconda3/envs/CAN_Reverse_Engineering/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 2273, in is_valid_linkage name_str) ValueError: Linkage 'Z' contains negative distances.

I believe this is caused by floating point precision limitations on very small positive numbers causing some distances to appear negative when added to the Z linkage.

I have fixed this in by changing line 80 in SemanticAnalysis.py to
Y = clip(ssd.squareform(X), 0, None)
and adding the associated import from numpy on line 2
from numpy import ndarray, zeros, clip

Since the numbers in question are so incredibly close to zero, clipping them to 0 does not cause any noticeable loss in the quality of the output data.

I have submitted the pull request linked at the top of this issue with the described changes.

**Comment by brent-stone** [comment]
Thanks for the fix! Sorry for the slow response. I'll merge this weekend.

**Comment by brent-stone** [comment]
Merged. Thanks for squishing the bug.
